### ISSUE TITLE
Nullpointer scanning JAX-RS annotated method

### ISSUE THREAD

**Issue by neon-dev** [smallrye/smallrye-open-api#290]
Upgrading a project from Thorntail 2.5.0.Final to 2.6.0.Final, I get the following error:
<details>
  <summary>Stack trace</summary>

```
2020-04-08 14:42:39,432 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Thorntail 2.6.0.Final (WildFly Core 10.0.3.Final) started in 1523ms - Started 279 of 410 services (249 services are lazy, passive or on-demand)
2020-04-08 14:42:40,894 ERROR [stderr] (main) org.wildfly.swarm.container.DeploymentException: java.lang.NullPointerException
2020-04-08 14:42:40,894 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:301)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:174)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:107)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer$Proxy$_$$_WeldClientProxy.deploy(Unknown Source)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:476)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:747)
2020-04-08 14:42:40,895 ERROR [stderr] (main) Caused by: java.lang.NullPointerException
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.createResponseFromJaxRsMethod(OpenApiAnnotationScanner.java:934)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:688)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
2020-04-08 14:42:40,895 ERROR [stderr] (main) 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsResourceClass(OpenApiAnnotationScanner.java:420)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:221)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromAnnotations(OpenApiProcessor.java:72)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at org.wildfly.swarm.microprofile.openapi.runtime.OpenApiDeploymentProcessor.process(OpenApiDeploymentProcessor.java:101)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at org.wildfly.swarm.microprofile.openapi.runtime.OpenApiDeploymentProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:233)
2020-04-08 14:42:40,896 ERROR [stderr] (main) 	... 5 more
```
</details>

Debugging it, I found out it comes from this method (simplified example):
```java
@GET
@Path("/id")
@APIResponse(responseCode = "200", ref = "idResponse")
public TextNode id() {
  return TextNode.valueOf("someId");
}
```

```java
@ApplicationPath("rest")
@OpenAPIDefinition(
    info = @Info(title = "Example", version = "1.0"),
    components = @Components(
        responses = @APIResponse(
                name = "idResponse",
                description = "Returns some ID.",
                content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(ref = "id"), example = "\"abc\"")
            ),
        schemas = @Schema(name = "id", implementation = String.class, description = "Some ID")
    )
)
public class Application extends javax.ws.rs.core.Application {
}
```
I see two issues here:
1. `SchemaFactory.typeToSchema(this.index, returnType, this.extensions)` returns `null` for `com.fasterxml.jackson.databind.node.TextNode`. TextNode doesn't throw an exception on Thorntail 2.5.0 (just tested it).
2. `returnType` should be `String.class` from the @Schema ref, not TextNode

**Comment by MikeEdgar** [comment]
@neon-dev , this looks like a duplicate of #248, fixed in #251. You should get good results by updating to `1.1.21` or `1.2.1`.

**Comment by neon-dev** [comment]
Indeed looks like it. Sorry, I didn't find the issue because of using the wrong keywords I guess.
Can I make Thorntail use the newer version by manually importing via Maven, or will it cause incompabilities with a Thorntail fraction?

**Comment by MikeEdgar** [comment]
I would try by adding the latest release of smallrye-open-api to `dependencyManagement`. I don't think there have been any changes significant enough to cause an issue in Thorntail, but never say "never" :)

**Comment by neon-dev** [comment]
Adding it there doesn't change anything. Adding it under regular `dependencies` it throws a log manager error: `java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"`
Nevertheless I looked at #251 and there's no fix for issue part 2) of my original post.

**Comment by MikeEdgar** [comment]
I overlooked the second part. It definitely looks like a bug and will need some investigation.

**Comment by MikeEdgar** [comment]
@neon-dev, running your example in the current `1.x` branch gives me the following output:

```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Example",
    "version" : "1.0"
  },
  "components" : {
    "schemas" : {
      "id" : {
        "description" : "Some ID",
        "type" : "string"
      }
    },
    "responses" : {
      "idResponse" : {
        "description" : "Returns some ID.",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/id"
            },
            "example" : "\"abc\""
          }
        }
      }
    }
  }
}
```
It appears the second issue was also resolved at some point as well. Try and see if excluding the SmallRye dependency from the `microprofile-openapi` Thorntail dependency (in addition to including the current SmallRye version) helps with the error you reported earlier.

**Comment by neon-dev** [comment]
Doesn't seem to be easily excluded.
```xml
<dependency>
  <groupId>io.thorntail</groupId>
  <artifactId>microprofile-openapi</artifactId>
  <exclusions>
    <exclusion>
      <groupId>io.smallrye</groupId>
      <artifactId>smallrye-open-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>io.smallrye</groupId>
  <artifactId>smallrye-open-api</artifactId>
  <version>1.2.1</version>
</dependency>
```
This still fails with the same error but when checking the line from the stack trace, it doesn't match with the sources for `1.2.1`.
This tells me Thorntail still uses an older version. I couldn't find out how or why.

**Comment by MikeEdgar** [comment]
In a simple test, it looks like the generated war file contains both versions. I'm guessing that it's due to how the `thorntail-maven-plugin` works. Your best bet may be to open an issue with Thorntail and see if they can advise how to override dependencies like this.

**Comment by neon-dev** [comment]
I'm currently too busy for troubleshooting this, so I'll just close this issue and reopen it in case it's not fixed once I get the chance to test it. No need to update dependencies right now, so I'll just wait a bit.

**Comment by Ladicek** [comment]
I just found this ticket. I'm afraid it isn't easily possible to override the SmallRye OpenAPI version used in Thorntail -- at runtime, what matters is not the Maven dependency, but the JBoss Modules module dependency. I'll make sure that for Thorntail 2.7.0, we'll have at least SmallRye OpenAPI 1.1.21.

**Comment by fabiobrz** [comment]
> I just found this ticket. I'm afraid it isn't easily possible to override the SmallRye OpenAPI version used in Thorntail -- at runtime, what matters is not the Maven dependency, but the JBoss Modules module dependency. I'll make sure that for Thorntail 2.7.0, we'll have at least SmallRye OpenAPI 1.1.21.

Hi @Ladicek, I don't know if this can fit here but have a look to 1.1.22, too. Just released and fixing another similar issue with annotation scanner. My 2 cents.

**Comment by Ladicek** [comment]
Yea, I have also just noticed 1.1.22 has been released, and have already added that to my commit. Thanks!
